mpu9250driver:
  ros__parameters:
    acceleration_x_offset: 2124
    acceleration_y_offset: 9897
    acceleration_z_offset: -3509
    gyroscope_x_drift_correction: -599
    gyroscope_x_offset: -64
    gyroscope_y_drift_correction: 324
    gyroscope_y_offset: 122
    gyroscope_z_drift_correction: -133
    gyroscope_z_offset: 199
    magnetometer_x_offset: 0
    magnetometer_y_offset: 0
    magnetometer_z_offset: 0
